-- Demo seed data removed.
-- This file previously seeded @inspire2live.org demo accounts (Sophie, Maria, Peter, Kai, Nadia, Admin).
-- All demo accounts have been removed. Only real users exist in the system.
