-- Demo layer: I2L World Campus WhatsApp mock content
--
-- Purpose:
--   Product-demo content derived from World Campus WhatsApp screenshots.
--   Rows are intentionally tagged and ID-scoped so they can be removed after the demo.
--
-- Apply:
--   psql "$DATABASE_URL" -f supabase/demo/world-campus-whatsapp-seed.sql
--
-- Remove:
--   psql "$DATABASE_URL" -f supabase/demo/world-campus-whatsapp-cleanup.sql

begin;

-- The seed is idempotent through deterministic IDs and unique provider_message_id
-- values. Run the cleanup script first when you want to remove any prior version
-- of the layer before reseeding.

with demo_author as (
  select id
  from public.profiles
  where user_type = 'comms'
     or comms_team = true
     or role = 'PlatformAdmin'
  order by
    case when email = 'marsu101@proton.me' then 0 else 1 end,
    created_at nulls last
  limit 1
),
insert_sessions as (
  insert into public.campus_sessions (
    id,
    session_date,
    theme,
    participating_hub_ids,
    summary,
    action_items_for_publication,
    recording_url,
    slides_media_id,
    initiative_ids,
    published_outputs,
    created_by,
    created_at,
    updated_at
  )
  values
    (
      '90000000-0000-4000-8000-000000000101',
      '2026-05-27',
      'May World Campus: multi-cancer early detection and patient voice',
      '{}',
      'Dr. Mao Mao session recap shared in the World Campus channel. Members highlighted multi-cancer early detection, open access medicines, and the need to keep patient voices close to research and decision tables.',
      array[
        'Review Nigeria imPACT report and decide whether to include it in the June briefing.',
        'Turn Stephen Friend Genetic Heroes video into a short founder-amplification post.',
        'Prepare a short thank-you note for Monica birthday wishes and cake photo thread.'
      ],
      'https://inspire2live.org/our-world-campus/library/dr-mao-mao-on-the-future-of-multi-cancer-early-detection/',
      null,
      '{}',
      '{}',
      (select id from demo_author),
      '2026-05-22 20:55:00+00',
      '2026-05-22 20:55:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000102',
      '2026-06-24',
      'June World Campus: congress follow-up and Nigeria imPACT signals',
      '{}',
      'Agenda building in progress from article shares, media, and campus-session follow-up. Core topics are GUIDE.MRD update, Nigeria hub report, Stephen Friend video, and Monica newsletter feature.',
      array[
        'Review May decisions: GUIDE.MRD report, newsletter schedule, congress plan.',
        'Discuss Nigeria imPACT report publication route.',
        'Agree whether Dr. Mao Mao session becomes newsletter, LinkedIn, or library item.'
      ],
      null,
      null,
      '{}',
      '{}',
      (select id from demo_author),
      '2026-05-24 10:00:00+00',
      '2026-05-24 10:00:00+00'
    )
  on conflict (id) do update set
    session_date = excluded.session_date,
    theme = excluded.theme,
    summary = excluded.summary,
    action_items_for_publication = excluded.action_items_for_publication,
    recording_url = excluded.recording_url,
    created_by = excluded.created_by,
    updated_at = excluded.updated_at
  returning id
),
insert_members as (
  insert into public.campus_members (
    id,
    name,
    country,
    organisation,
    role_description,
    whatsapp_id,
    platform_profile_id,
    date_welcomed,
    welcomed_by_peter,
    initiative_affiliations,
    notes,
    last_channel_activity,
    created_at,
    updated_at
  )
  values
    (
      '90000000-0000-4000-8000-000000000201',
      'Monica Kleijn Evason',
      'United Kingdom',
      'World Campus network',
      'Patient engagement and community connector',
      'demo-world-campus:monica',
      null,
      '2026-05-21',
      false,
      '{}',
      'Birthday wishes thread created strong engagement across World Campus members; useful for newsletter human-interest segment.',
      '2026-05-21',
      '2026-05-21 15:10:00+00',
      '2026-05-21 15:10:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000202',
      'Atefeh',
      null,
      'IARC60 / patient engagement',
      'Shares LinkedIn patient-engagement and cancer research signals',
      'demo-world-campus:atefeh',
      null,
      '2026-05-22',
      false,
      '{}',
      'Shared IARC60 LinkedIn post about patient voices and real-life needs in research.',
      '2026-05-22',
      '2026-05-22 08:47:00+00',
      '2026-05-22 08:47:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000203',
      'Ifeoma',
      'Nigeria',
      'Nigeria hub',
      'Shares cancer-control and imPACT report updates',
      'demo-world-campus:ifeoma',
      null,
      '2026-05-23',
      false,
      '{}',
      'Shared Nigeria imPACT Review Report 2025 and IAEA PDF reference for NCCP 2026-2030 context.',
      '2026-05-23',
      '2026-05-23 20:57:00+00',
      '2026-05-23 20:57:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000204',
      'Ieva',
      'Lithuania',
      'World Campus',
      'Session and library signal contributor',
      'demo-world-campus:ieva',
      null,
      '2026-05-20',
      false,
      '{}',
      'Shared Dr. Mao Mao World Campus session item on multi-cancer early detection.',
      '2026-05-20',
      '2026-05-20 20:55:00+00',
      '2026-05-20 20:55:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000205',
      'Peter Kapitein',
      'Netherlands',
      'Inspire2Live',
      'Founder signal layer and World Campus ambassador',
      'demo-world-campus:peter',
      null,
      '2026-05-20',
      true,
      '{}',
      'Shared Stephen Friend Genetic Heroes context and amplified the Dr. Mao Mao session response.',
      '2026-05-23',
      '2026-05-20 09:13:00+00',
      '2026-05-23 20:56:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000206',
      'MARTI CONNECTING AFRICA',
      'Germany',
      'World Campus',
      'Community media contributor',
      'demo-world-campus:marti',
      null,
      '2026-05-21',
      false,
      '{}',
      'Shared birthday cake photo in Monica thread; keep as internal-only media unless rights are cleared.',
      '2026-05-21',
      '2026-05-21 16:28:00+00',
      '2026-05-21 16:28:00+00'
    )
  on conflict (id) do update set
    name = excluded.name,
    country = excluded.country,
    organisation = excluded.organisation,
    role_description = excluded.role_description,
    whatsapp_id = excluded.whatsapp_id,
    date_welcomed = excluded.date_welcomed,
    welcomed_by_peter = excluded.welcomed_by_peter,
    notes = excluded.notes,
    last_channel_activity = excluded.last_channel_activity,
    updated_at = excluded.updated_at
  returning id
),
insert_media as (
  insert into public.media_assets (
    id,
    title,
    asset_type,
    sharepoint_url,
    storage_path,
    event_id,
    session_id,
    initiative_id,
    contributed_by,
    rights_status,
    tags,
    usage_count,
    created_at
  )
  values
    (
      '90000000-0000-4000-8000-000000000301',
      'Dr. Mao Mao World Campus session card',
      'photo',
      'https://inspire2live.org/our-world-campus/library/dr-mao-mao-on-the-future-of-multi-cancer-early-detection/',
      'demo/world-campus-whatsapp/dr-mao-mao-session-card.jpg',
      null,
      '90000000-0000-4000-8000-000000000101',
      null,
      (select id from demo_author),
      'approved_for_publication',
      array['demo_world_campus_whatsapp', 'world-campus', 'mced', 'dr-mao-mao'],
      2,
      '2026-05-20 20:55:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000302',
      'Monica birthday cake photo',
      'photo',
      null,
      'demo/world-campus-whatsapp/monica-birthday-cake.jpg',
      null,
      null,
      null,
      (select id from demo_author),
      'internal_only',
      array['demo_world_campus_whatsapp', 'world-campus', 'birthday', 'monica'],
      1,
      '2026-05-21 16:28:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000303',
      'Nigeria imPACT review report PDF',
      'report',
      'https://www.iaea.org/sites/default/files/2025-11/nigeria-impact-241024.pdf',
      'demo/world-campus-whatsapp/nigeria-impact-241024.pdf',
      null,
      null,
      null,
      (select id from demo_author),
      'approved_for_publication',
      array['demo_world_campus_whatsapp', 'world-campus', 'nigeria', 'impact', 'nccp'],
      3,
      '2026-05-23 20:57:00+00'
    )
  on conflict (id) do update set
    title = excluded.title,
    asset_type = excluded.asset_type,
    sharepoint_url = excluded.sharepoint_url,
    storage_path = excluded.storage_path,
    session_id = excluded.session_id,
    contributed_by = excluded.contributed_by,
    rights_status = excluded.rights_status,
    tags = excluded.tags,
    usage_count = excluded.usage_count
  returning id
),
update_session_media as (
  update public.campus_sessions
  set slides_media_id = '90000000-0000-4000-8000-000000000301'
  where id = '90000000-0000-4000-8000-000000000101'
  returning id
),
insert_intake as (
  insert into public.intake_items (
    id,
    captured_at,
    capture_method,
    sender_name,
    sender_whatsapp_id,
    raw_content,
    source_url,
    content_type,
    classification_confidence,
    is_peter_kapitein,
    status,
    reviewed_by,
    reviewed_at,
    routed_to_type,
    routed_to_id,
    dismissed_reason,
    attached_media_ref,
    classifier_version,
    classifier_status,
    classifier_reasoning,
    classifier_rule_ids,
    provider_message_id,
    created_at
  )
  values
    (
      '90000000-0000-4000-8000-000000000401',
      '2026-05-20 09:09:00+00',
      'manual',
      'Peter Kapitein',
      'demo-world-campus:peter',
      'You might find this interesting. We all know our hero and ambassador Stephen Friend. In 2014 he started looking for people who should get sick but are not: Genetic Heroes. This project now uses more than 1.5 million WGS people with their clinical data and found many of these heroes. Stephen now works on finding what inhibits these heroes from getting sick and through this finding medicines that can help patients. These medicines will stay open access for the global patient.',
      'https://youtu.be/YAqdvqn2YMU',
      'article_share',
      'high',
      true,
      'unreviewed',
      null,
      null,
      null,
      null,
      null,
      null,
      'demo-world-campus-whatsapp-v1',
      'auto_classified',
      '[{"layer":"demo_world_campus_whatsapp","source":"world_campus_whatsapp","reason":"Peter founder signal and YouTube article share from screenshot"}]'::jsonb,
      array['demo_world_campus_whatsapp', 'peter-founder-signal'],
      'demo-world-campus-whatsapp:genetic-heroes',
      '2026-05-20 09:09:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000402',
      '2026-05-22 08:47:00+00',
      'manual',
      'Atefeh',
      'demo-world-campus:atefeh',
      '#inspire2live #ifaboutusnotwithoutus #iarc60 #patientengagement #cancerresearch. At Inspire2Live, bringing patients voices and real-life needs to research and decision-making tables is not optional. LinkedIn post already has 5 reactions.',
      'https://www.linkedin.com/feed/update/urn:li:activity:7463118211056652289',
      'article_share',
      'high',
      false,
      'unreviewed',
      null,
      null,
      null,
      null,
      null,
      null,
      'demo-world-campus-whatsapp-v1',
      'auto_classified',
      '[{"layer":"demo_world_campus_whatsapp","source":"world_campus_whatsapp","reason":"LinkedIn patient engagement signal from Atefeh screenshot"}]'::jsonb,
      array['demo_world_campus_whatsapp', 'linkedin-signal'],
      'demo-world-campus-whatsapp:atefeh-iarc60-linkedin',
      '2026-05-22 08:47:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000403',
      '2026-05-23 20:57:00+00',
      'manual',
      'Ifeoma',
      'demo-world-campus:ifeoma',
      'Nigeria imPACT Review Report 2025 - National Institute for Cancer Research and Treatment. Baseline data for NCCP 2026-2030. Information that can be of interest to us.',
      'https://www.nicrat.gov.ng/06/https-www-nicrat-gov-ng-wp-content-uploads-2023-08-nigeria-impact-review-report-pdf/',
      'article_share',
      'high',
      false,
      'unreviewed',
      null,
      null,
      null,
      null,
      null,
      'https://www.iaea.org/sites/default/files/2025-11/nigeria-impact-241024.pdf',
      'demo-world-campus-whatsapp-v1',
      'auto_classified',
      '[{"layer":"demo_world_campus_whatsapp","source":"world_campus_whatsapp","reason":"Nigeria imPACT report and PDF link from screenshot"}]'::jsonb,
      array['demo_world_campus_whatsapp', 'report-share'],
      'demo-world-campus-whatsapp:nigeria-impact-report',
      '2026-05-23 20:57:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000404',
      '2026-05-20 20:55:00+00',
      'manual',
      'Ieva',
      'demo-world-campus:ieva',
      'Dear World Campus members, here you can find the latest World Campus Session with Dr. Mao Mao: The future of multi-cancer early detection.',
      'https://inspire2live.org/our-world-campus/library/dr-mao-mao-on-the-future-of-multi-cancer-early-detection/',
      'event_report',
      'high',
      false,
      'routed',
      (select id from demo_author),
      '2026-05-21 08:00:00+00',
      'campus_session',
      '90000000-0000-4000-8000-000000000101',
      null,
      'demo/world-campus-whatsapp/dr-mao-mao-session-card.jpg',
      'demo-world-campus-whatsapp-v1',
      'auto_classified',
      '[{"layer":"demo_world_campus_whatsapp","source":"world_campus_whatsapp","reason":"World Campus session link from screenshot"}]'::jsonb,
      array['demo_world_campus_whatsapp', 'campus-session'],
      'demo-world-campus-whatsapp:dr-mao-mao-session',
      '2026-05-20 20:55:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000405',
      '2026-05-21 15:13:00+00',
      'manual',
      'Peter Kapitein',
      'demo-world-campus:peter',
      'Oh, a happy belated birthday indeed dear Monica. I hope it was awesome.',
      null,
      'member_intro',
      'medium',
      true,
      'routed',
      (select id from demo_author),
      '2026-05-21 16:00:00+00',
      'campus_member',
      '90000000-0000-4000-8000-000000000201',
      null,
      null,
      'demo-world-campus-whatsapp-v1',
      'auto_classified',
      '[{"layer":"demo_world_campus_whatsapp","source":"world_campus_whatsapp","reason":"Birthday thread around Monica, useful as human-interest campus signal"}]'::jsonb,
      array['demo_world_campus_whatsapp', 'member-thread'],
      'demo-world-campus-whatsapp:monica-birthday-peter',
      '2026-05-21 15:13:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000406',
      '2026-05-21 15:15:00+00',
      'manual',
      'Barbara',
      'demo-world-campus:barbara',
      'Happy birthday for yesterday, dear Monica. May your birthday go forever too. Sending our love and hugs, Barbara and Mark.',
      null,
      'member_intro',
      'medium',
      false,
      'unreviewed',
      null,
      null,
      null,
      null,
      null,
      null,
      'demo-world-campus-whatsapp-v1',
      'auto_classified',
      '[{"layer":"demo_world_campus_whatsapp","source":"world_campus_whatsapp","reason":"Community birthday thread with strong engagement"}]'::jsonb,
      array['demo_world_campus_whatsapp', 'member-thread'],
      'demo-world-campus-whatsapp:monica-birthday-barbara',
      '2026-05-21 15:15:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000407',
      '2026-05-21 15:18:00+00',
      'manual',
      'Piarella Peralta',
      'demo-world-campus:piarella',
      'Dearest Monica, happy birthday still on your birthday week. Wishing you all the very best in life and thank you for being so full of energy and enthusiasm. With you around there is no way to feel any other way than happy.',
      null,
      'member_intro',
      'medium',
      false,
      'unreviewed',
      null,
      null,
      null,
      null,
      null,
      null,
      'demo-world-campus-whatsapp-v1',
      'auto_classified',
      '[{"layer":"demo_world_campus_whatsapp","source":"world_campus_whatsapp","reason":"Community birthday thread quote from screenshot"}]'::jsonb,
      array['demo_world_campus_whatsapp', 'member-thread'],
      'demo-world-campus-whatsapp:monica-birthday-piarella',
      '2026-05-21 15:18:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000408',
      '2026-05-21 16:28:00+00',
      'manual',
      'MARTI CONNECTING AFRICA',
      'demo-world-campus:marti',
      'Happy belated birthday Monica. Shared cake photo in the group thread.',
      null,
      'media_request',
      'medium',
      false,
      'routed',
      (select id from demo_author),
      '2026-05-21 17:00:00+00',
      'media_asset',
      '90000000-0000-4000-8000-000000000302',
      null,
      'demo/world-campus-whatsapp/monica-birthday-cake.jpg',
      'demo-world-campus-whatsapp-v1',
      'auto_classified',
      '[{"layer":"demo_world_campus_whatsapp","source":"world_campus_whatsapp","reason":"Cake photo media item from screenshot"}]'::jsonb,
      array['demo_world_campus_whatsapp', 'media'],
      'demo-world-campus-whatsapp:monica-cake-photo',
      '2026-05-21 16:28:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000409',
      '2026-05-20 12:40:00+00',
      'manual',
      'Woud Nyarogseya',
      'demo-world-campus:woud',
      'Thanks so much Peter.',
      null,
      'noise',
      'low',
      false,
      'dismissed',
      (select id from demo_author),
      '2026-05-20 13:00:00+00',
      null,
      null,
      'Short acknowledgement kept for raw-feed traceability only.',
      null,
      'demo-world-campus-whatsapp-v1',
      'auto_classified',
      '[{"layer":"demo_world_campus_whatsapp","source":"world_campus_whatsapp","reason":"Short reply in Stephen Friend thread"}]'::jsonb,
      array['demo_world_campus_whatsapp', 'noise'],
      'demo-world-campus-whatsapp:woud-thanks-peter',
      '2026-05-20 12:40:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000410',
      '2026-05-23 11:20:00+00',
      'manual',
      'I2L World Campus admin',
      'demo-world-campus:admin',
      'Link to the Annual Congress including the program shared in the group. Use this as a reminder for comms follow-up and participant routing.',
      'https://inspire2live.org/congresses/inspire2live-annual-congress/',
      'event_report',
      'medium',
      false,
      'unreviewed',
      null,
      null,
      null,
      null,
      null,
      null,
      'demo-world-campus-whatsapp-v1',
      'auto_classified',
      '[{"layer":"demo_world_campus_whatsapp","source":"world_campus_whatsapp","reason":"Annual Congress program link visible in group info screenshot"}]'::jsonb,
      array['demo_world_campus_whatsapp', 'annual-congress'],
      'demo-world-campus-whatsapp:annual-congress-program',
      '2026-05-23 11:20:00+00'
    )
  on conflict (id) do update set
    captured_at = excluded.captured_at,
    capture_method = excluded.capture_method,
    sender_name = excluded.sender_name,
    sender_whatsapp_id = excluded.sender_whatsapp_id,
    raw_content = excluded.raw_content,
    source_url = excluded.source_url,
    content_type = excluded.content_type,
    classification_confidence = excluded.classification_confidence,
    is_peter_kapitein = excluded.is_peter_kapitein,
    status = excluded.status,
    reviewed_by = excluded.reviewed_by,
    reviewed_at = excluded.reviewed_at,
    routed_to_type = excluded.routed_to_type,
    routed_to_id = excluded.routed_to_id,
    dismissed_reason = excluded.dismissed_reason,
    attached_media_ref = excluded.attached_media_ref,
    classifier_version = excluded.classifier_version,
    classifier_status = excluded.classifier_status,
    classifier_reasoning = excluded.classifier_reasoning,
    classifier_rule_ids = excluded.classifier_rule_ids,
    provider_message_id = excluded.provider_message_id,
    created_at = excluded.created_at
  returning id, provider_message_id, sender_whatsapp_id, sender_name, raw_content, captured_at
),
insert_calendar as (
  insert into public.content_calendar (
    id,
    title,
    channels,
    status,
    scheduled_at,
    published_at,
    body_draft,
    author_id,
    source_intake_id,
    source_initiative_id,
    source_event_id,
    tags,
    source_link,
    attached_media_refs,
    whatsapp_groups,
    created_at,
    updated_at
  )
  values
    (
      '90000000-0000-4000-8000-000000000501',
      'Stephen Friend - Genetic Heroes',
      array['linkedin', 'newsletter'],
      'in_review',
      '2026-05-27 09:00:00+00',
      null,
      'Founder amplification draft: Peter shared Stephen Friend Genetic Heroes video with context on 1.5M WGS participants, clinical data, and open-access medicine paths for global patients. Keep tone scientific, short, and human.',
      (select id from demo_author),
      '90000000-0000-4000-8000-000000000401',
      null,
      null,
      array['demo_world_campus_whatsapp', 'genetic-heroes', 'founder-signal'],
      'https://youtu.be/YAqdvqn2YMU',
      '{}',
      array['I2L World Campus'],
      '2026-05-24 09:00:00+00',
      '2026-05-24 09:00:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000502',
      'Nigeria imPACT Review 2025',
      array['newsletter', 'library'],
      'scheduled',
      '2026-05-29 08:00:00+00',
      null,
      'Short report note: Ifeoma shared Nigeria imPACT Review Report 2025 with baseline context for NCCP 2026-2030. Link NICRAT page and IAEA PDF, and ask Nigeria hub whether a follow-up quote is available.',
      (select id from demo_author),
      '90000000-0000-4000-8000-000000000403',
      null,
      null,
      array['demo_world_campus_whatsapp', 'nigeria', 'impact', 'report'],
      'https://www.nicrat.gov.ng/06/https-www-nicrat-gov-ng-wp-content-uploads-2023-08-nigeria-impact-review-report-pdf/',
      array['https://www.iaea.org/sites/default/files/2025-11/nigeria-impact-241024.pdf'],
      array['I2L World Campus'],
      '2026-05-24 09:10:00+00',
      '2026-05-24 09:10:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000503',
      'Dr. Mao Mao World Campus recap',
      array['website', 'newsletter', 'linkedin'],
      'published',
      '2026-05-22 12:00:00+00',
      '2026-05-22 12:30:00+00',
      'Published session recap for Dr. Mao Mao on the future of multi-cancer early detection. Reuse card image and link to World Campus library page.',
      (select id from demo_author),
      '90000000-0000-4000-8000-000000000404',
      null,
      null,
      array['demo_world_campus_whatsapp', 'world-campus-session', 'mced'],
      'https://inspire2live.org/our-world-campus/library/dr-mao-mao-on-the-future-of-multi-cancer-early-detection/',
      array['demo/world-campus-whatsapp/dr-mao-mao-session-card.jpg'],
      array['I2L World Campus'],
      '2026-05-22 12:00:00+00',
      '2026-05-22 12:30:00+00'
    ),
    (
      '90000000-0000-4000-8000-000000000504',
      'Monica birthday community note',
      array['newsletter'],
      'draft',
      '2026-06-03 09:00:00+00',
      null,
      'Human-interest draft from the World Campus birthday thread. Keep internal unless Monica approves public mention and cake/photo rights are cleared.',
      (select id from demo_author),
      '90000000-0000-4000-8000-000000000406',
      null,
      null,
      array['demo_world_campus_whatsapp', 'world-campus', 'birthday', 'member-story'],
      null,
      array['demo/world-campus-whatsapp/monica-birthday-cake.jpg'],
      array['I2L World Campus'],
      '2026-05-24 09:20:00+00',
      '2026-05-24 09:20:00+00'
    )
  on conflict (id) do update set
    title = excluded.title,
    channels = excluded.channels,
    status = excluded.status,
    scheduled_at = excluded.scheduled_at,
    published_at = excluded.published_at,
    body_draft = excluded.body_draft,
    author_id = excluded.author_id,
    source_intake_id = excluded.source_intake_id,
    tags = excluded.tags,
    source_link = excluded.source_link,
    attached_media_refs = excluded.attached_media_refs,
    whatsapp_groups = excluded.whatsapp_groups,
    updated_at = excluded.updated_at
  returning id
),
insert_webhook_events as (
  insert into public.whatsapp_webhook_events (
    provider,
    provider_message_id,
    sender_whatsapp_id,
    sender_name,
    payload,
    intake_item_id,
    processing_status,
    failure_reason,
    received_at,
    processed_at
  )
  select
    'whatsapp_demo_export',
    provider_message_id,
    sender_whatsapp_id,
    sender_name,
    jsonb_build_object(
      'layer', 'demo_world_campus_whatsapp',
      'group_name', 'I2L World Campus',
      'source', 'product_demo_seed',
      'raw_content', raw_content
    ),
    id,
    'accepted',
    null,
    captured_at,
    captured_at
  from insert_intake
  where provider_message_id is not null
  on conflict (provider_message_id) do update set
    sender_whatsapp_id = excluded.sender_whatsapp_id,
    sender_name = excluded.sender_name,
    payload = excluded.payload,
    intake_item_id = excluded.intake_item_id,
    processing_status = excluded.processing_status,
    received_at = excluded.received_at,
    processed_at = excluded.processed_at
  returning id
)
select
  (select count(*) from insert_sessions) as campus_sessions,
  (select count(*) from insert_members) as campus_members,
  (select count(*) from insert_media) as media_assets,
  (select count(*) from insert_intake) as intake_items,
  (select count(*) from insert_calendar) as calendar_items,
  (select count(*) from insert_webhook_events) as webhook_events;

commit;
